### ISSUE TITLE
求代码

### ISSUE THREAD

**Issue by sayhelloto1988** [Zhijin-Ge/STM#1]
您好！请问可以给一份STM-SIM的代码吗？ 我改的那个不知道怎么和您原论文里的结果有点差距，不知道是哪里没有设置好？

**Comment by sayhelloto1988** [comment]
`for i in range(num_iter):
        noise = 0
        for n in range(N):
            for i in torch.arange(5):
                nes_x = x / torch.pow(2, i)
                # randomize style:
                x_aug = augmentor(nes_x)
                x_new = gamma * x + (1 - gamma) * Resize(x_aug.detach()).clone() + \
                    torch.randn_like(x).uniform_(-eps * beta, eps * beta)
                x_new = V(x_new, requires_grad=True)

                output_v3 = model(x_new)
                loss = F.cross_entropy(output_v3, gt)
                noise += torch.autograd.grad(loss, x_new,
                                             retain_graph=False, create_graph=False)[0]
            noise = noise / 5
        noise = noise / N

        noise = noise / torch.abs(noise).mean([1, 2, 3], keepdim=True)
        noise = momentum * grad + noise
        grad = noise

        x = x + alpha * torch.sign(noise)
        x = clip_by_tensor(x, min, max)`

**Comment by sayhelloto1988** [comment]
``for i in range(num_iter):
        noise = 0
        for n in range(N):
            for i in torch.arange(5):
                nes_x = x / torch.pow(2, i)
                # randomize style:
                x_aug = augmentor(nes_x)
                x_new = gamma * x + (1 - gamma) * Resize(x_aug.detach()).clone() + \
                    torch.randn_like(x).uniform_(-eps * beta, eps * beta)
                x_new = V(x_new, requires_grad=True)

                output_v3 = model(x_new)
                loss = F.cross_entropy(output_v3, gt)
                noise += torch.autograd.grad(loss, x_new,
                                             retain_graph=False, create_graph=False)[0]
            noise = noise / 5
        noise = noise / N

        noise = noise / torch.abs(noise).mean([1, 2, 3], keepdim=True)
        noise = momentum * grad + noise
        grad = noise

        x = x + alpha * torch.sign(noise)
        x = clip_by_tensor(x, min, max)`

**Comment by sayhelloto1988** [comment]
![image](https://github.com/Zhijin-Ge/STM/assets/112956711/2ae93ec4-20c1-45ea-bfdb-ad001d1f4983)

**Comment by Zhijin-Ge** [comment]
Thanks for your interest in our work. Since I couldn't find the previous code, I rewrote it, and this code should be able to reproduce the results from the paper. We hope this information is useful for you!
![STM-SIM](https://github.com/Zhijin-Ge/STM/assets/42350897/b4381ed1-5109-430c-9415-6a9d9219d48b)

**Comment by sayhelloto1988** [comment]
![image](https://github.com/Zhijin-Ge/STM/assets/112956711/11079f9e-27f1-4606-a45c-d57f33fff5d8)

**Comment by sayhelloto1988** [comment]
我昨天就是用上面的那个跑的，感觉结果差的有点多啊，我看了下我写的，和您评论给的代码是一样的呀。但是，我用Inc-V3，跑出来的数据，在三个ens的鲁棒模型上攻击成功率都只有20%的样子。想请教下我是不是那儿没设置好？

**Comment by Zhijin-Ge** [comment]
你好，我现在已经更新了verify.py的代码，其中主要的问题是在验证ens鲁棒模型的时候gt要加1才是它的真实标签，你现在重新运行一下试试看。另外我上面使用的STM-SIM代码和你截图里的有些是不一样哦，你可以参考我提供的代码改一下。希望能帮到你，谢谢！

**Comment by Lzixuan12** [comment]
FileNotFoundError: [Errno 2] No such file or directory: './models/tf_inception_v3.npy'

> 我昨天就是用上面的那个跑的，感觉结果差的有点多啊，我看了下我写的，和您评论给的代码是一样的呀。但是，我用Inc-V3，跑出来的数据，在三个ens的鲁棒模型上攻击成功率都只有20%的样子。想请教下我是不是那儿没设置好？

Excuse me，Can I ask you how to solve this error?FileNotFoundError: [Errno 2] No such file or directory: './models/tf_inception_v3.npy'

**Comment by sayhelloto1988** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: './models/tf_inception_v3.npy'
> 
> > 我昨天就是用上面的那个跑的，感觉结果差的有点多啊，我看了下我写的，和您评论给的代码是一样的呀。但是，我用Inc-V3，跑出来的数据，在三个ens的鲁棒模型上攻击成功率都只有20%的样子。想请教下我是不是那儿没设置好？
> 
> Excuse me，Can I ask you how to solve this error?FileNotFoundError: [Errno 2] No such file or directory: './models/tf_inception_v3.npy'

you can download the weights in this:"https://github.com/ylhz/tf_to_pytorch_model/releases".  the result of attack method STM-SIM, will be a bit different from the result in the paper. it lower than the result in the papper about 6%.

**Comment by Lzixuan12** [comment]
> > FileNotFoundError: [Errno 2] No such file or directory: './models/tf_inception_v3.npy'
> > > 我昨天就是用上面的那个跑的，感觉结果差的有点多啊，我看了下我写的，和您评论给的代码是一样的呀。但是，我用Inc-V3，跑出来的数据，在三个ens的鲁棒模型上攻击成功率都只有20%的样子。想请教下我是不是那儿没设置好？
> > 
> > 
> > Excuse me，Can I ask you how to solve this error?FileNotFoundError: [Errno 2] No such file or directory: './models/tf_inception_v3.npy'
> 
> you can download the weights in this:"https://github.com/ylhz/tf_to_pytorch_model/releases". the result of attack method STM-SIM, will be a bit different from the result in the paper. it lower than the result in the papper about 6%.

thank you very much
